### ISSUE TITLE
Feature Request: Keep sorted SNP matrix

### ISSUE THREAD

**Issue by erinyoung** [DrB-S/heatcluster#23]
From https://github.com/UPHL-BioNGS/Grandeur/issues/154 
> Could this sorted matrix be output as a .csv

This sounds like something that would be "easy" to implement. Can I also request this as a feature?

Something like
```python
df.to_csv(sorted_matrix.csv, index=False)
```

**Comment by DrB-S** [comment]
Good idea. Will do.

**Comment by DrB-S** [comment]
Version 1.0.2 includes sorted_matrix.csv output.
